---
deployment:
  tasks:
    #- export DEPLOYPATH=/home/megaaxmg/teombley.asia/iraffle/admin/
    - export DEPLOYPATH=/home/u5233116/web/admin/
    - /bin/cp -R * $DEPLOYPATH
    #- /bin/rsync -a --exclude 'conn.php' public/ $DEPLOYPATH
